let
    reset_state()
    rho_vovo = output_tensor("rho_vovo", ("v", "o", "v", "o"))
    F_vv = input_tensor("F_vv", ("v", "v"))
    cs_vovo = input_tensor("cs_vovo", ("v", "o", "v", "o"))
    F_oo = input_tensor("F_oo", ("o", "o"))
    cs_vo = input_tensor("cs_vo", ("v", "o"))
    g_vooo = input_tensor("g_vooo", ("v", "o", "o", "o"))
    g_vvvo = input_tensor("g_vvvo", ("v", "v", "v", "o"))
    L_voov = input_tensor("L_voov", ("v", "o", "o", "v"))
    g_voov = input_tensor("g_voov", ("v", "o", "o", "v"))
    g_vvoo = input_tensor("g_vvoo", ("v", "v", "o", "o"))
    F_ov = input_tensor("F_ov", ("o", "v"))
    t_vovo = input_tensor("t_vovo", ("v", "o", "v", "o"))
    ct_vovo = input_tensor("ct_vovo", ("v", "o", "v", "o"))
    s_vo = noio_tensor("wf%s1", ("v", "o"))
    ct_vo = input_tensor("ct_vo", ("v", "o"))
    s_vovo = input_tensor("s_vovo", ("v", "o", "v", "o"))
    g_oooo = input_tensor("g_oooo", ("o", "o", "o", "o"))
    g_vvvv = input_tensor("g_vvvv", ("v", "v", "v", "v"))
    L_vvov = input_tensor("L_vvov", ("v", "v", "o", "v"))
    L_ooov = input_tensor("L_ooov", ("o", "o", "o", "v"))
    g_vvov = input_tensor("g_vvov", ("v", "v", "o", "v"))
    g_ovoo = input_tensor("g_ovoo", ("o", "v", "o", "o"))
    g_ooov = input_tensor("g_ooov", ("o", "o", "o", "v"))
    u_vovo = noio_tensor("wf%u_aibj", ("v", "o", "v", "o"))
    v_vovo = input_tensor("v_vovo", ("v", "o", "v", "o"))
    L_ovov = input_tensor("L_ovov", ("o", "v", "o", "v"))
    g_ovov = input_tensor("g_ovov", ("o", "v", "o", "v"))
    @tensor opt=(a=>10χ,b=>10χ,c=>10χ,d=>10χ,i=>χ,j=>χ,k=>χ,l=>χ) backend=eTbackend begin
        rho_vovo[a,i,b,j] += 2*F_vv[a,c]*cs_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -2*F_oo[k,i]*cs_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += -cs_vo[a,k]*g_vooo[b,j,k,i]
        rho_vovo[a,i,b,j] += cs_vo[c,i]*g_vvvo[a,c,b,j]
        rho_vovo[a,i,b,j] += 2*L_voov[a,i,k,c]*cs_vovo[b,j,c,k]
        rho_vovo[a,i,b,j] += -2*cs_vovo[a,k,c,i]*g_voov[b,j,k,c]
        rho_vovo[a,i,b,j] += -2*cs_vovo[a,k,c,j]*g_vvoo[b,c,k,i]
        rho_vovo[a,i,b,j] += -F_ov[k,c]*cs_vo[a,k]*t_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -F_ov[k,c]*cs_vo[c,i]*t_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += -2*F_ov[k,c]*ct_vovo[a,i,b,k]*s_vo[c,j]
        rho_vovo[a,i,b,j] += -2*F_ov[k,c]*ct_vovo[a,i,c,j]*s_vo[b,k]
        rho_vovo[a,i,b,j] += -F_ov[k,c]*ct_vo[a,k]*s_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -F_ov[k,c]*ct_vo[c,i]*s_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += -ct_vo[a,k]*g_voov[b,j,k,c]*s_vo[c,i]
        rho_vovo[a,i,b,j] += -ct_vo[a,k]*g_vvoo[b,c,k,i]*s_vo[c,j]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_oooo[k,i,l,j]*s_vo[b,l]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_vvvv[a,c,b,d]*s_vo[d,j]
        rho_vovo[a,i,b,j] += -ct_vo[c,i]*g_vvoo[a,c,k,j]*s_vo[b,k]
        rho_vovo[a,i,b,j] += -ct_vo[c,i]*g_voov[b,j,k,c]*s_vo[a,k]
        rho_vovo[a,i,b,j] += L_vvov[a,c,k,d]*cs_vo[d,k]*t_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -L_ooov[k,i,l,c]*cs_vo[c,l]*t_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += 2*L_vvov[a,c,k,d]*ct_vovo[b,j,c,i]*s_vo[d,k]
        rho_vovo[a,i,b,j] += 2*L_vvov[a,c,k,d]*ct_vovo[b,j,d,k]*s_vo[c,i]
        rho_vovo[a,i,b,j] += L_vvov[a,c,k,d]*ct_vo[d,k]*s_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -2*L_ooov[k,i,l,c]*ct_vovo[a,k,b,j]*s_vo[c,l]
        rho_vovo[a,i,b,j] += -2*L_ooov[k,i,l,c]*ct_vovo[b,j,c,l]*s_vo[a,k]
        rho_vovo[a,i,b,j] += -L_ooov[k,i,l,c]*ct_vo[c,l]*s_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += -cs_vo[a,k]*g_vvov[b,c,k,d]*t_vovo[c,j,d,i]
        rho_vovo[a,i,b,j] += cs_vo[a,k]*g_ovoo[k,c,l,i]*t_vovo[b,j,c,l]
        rho_vovo[a,i,b,j] += cs_vo[a,k]*g_ovoo[k,c,l,j]*t_vovo[b,l,c,i]
        rho_vovo[a,i,b,j] += -cs_vo[c,i]*g_vvov[a,d,k,c]*t_vovo[b,j,d,k]
        rho_vovo[a,i,b,j] += -cs_vo[c,i]*g_vvov[b,d,k,c]*t_vovo[a,k,d,j]
        rho_vovo[a,i,b,j] += cs_vo[c,i]*g_ooov[k,j,l,c]*t_vovo[a,l,b,k]
        rho_vovo[a,i,b,j] += -cs_vo[a,k]*g_ooov[k,i,l,c]*u_vovo[b,j,c,l]
        rho_vovo[a,i,b,j] += cs_vo[c,i]*g_vvov[a,c,k,d]*u_vovo[b,j,d,k]
        rho_vovo[a,i,b,j] += -ct_vo[a,k]*g_vvov[b,c,k,d]*s_vovo[c,j,d,i]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_ovoo[k,c,l,i]*s_vovo[b,j,c,l]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_ovoo[k,c,l,j]*s_vovo[b,l,c,i]
        rho_vovo[a,i,b,j] += 2*ct_vovo[a,k,b,l]*g_ooov[k,i,l,c]*s_vo[c,j]
        rho_vovo[a,i,b,j] += -2*ct_vovo[a,k,c,i]*g_vvov[b,d,k,c]*s_vo[d,j]
        rho_vovo[a,i,b,j] += 2*ct_vovo[a,k,c,i]*g_ovoo[k,c,l,j]*s_vo[b,l]
        rho_vovo[a,i,b,j] += -2*ct_vovo[a,k,c,j]*g_vvov[b,c,k,d]*s_vo[d,i]
        rho_vovo[a,i,b,j] += 2*ct_vovo[a,k,c,j]*g_ooov[k,i,l,c]*s_vo[b,l]
        rho_vovo[a,i,b,j] += -ct_vo[c,i]*g_vvov[a,d,k,c]*s_vovo[b,j,d,k]
        rho_vovo[a,i,b,j] += -ct_vo[c,i]*g_vvov[b,d,k,c]*s_vovo[a,k,d,j]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_ooov[k,j,l,c]*s_vovo[a,l,b,k]
        rho_vovo[a,i,b,j] += -2*ct_vovo[c,i,d,j]*g_vvov[a,c,k,d]*s_vo[b,k]
        rho_vovo[a,i,b,j] += -ct_vo[a,k]*g_ooov[k,i,l,c]*v_vovo[b,j,c,l]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_vvov[a,c,k,d]*v_vovo[b,j,d,k]
        rho_vovo[a,i,b,j] += -2*L_ovov[k,c,l,d]*cs_vovo[a,k,d,l]*t_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -2*L_ovov[k,c,l,d]*cs_vovo[c,i,d,l]*t_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += 2*L_ovov[k,c,l,d]*cs_vovo[a,i,c,k]*u_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += -2*L_ovov[k,c,l,d]*ct_vovo[a,k,d,l]*s_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -2*L_ovov[k,c,l,d]*ct_vovo[c,i,d,l]*s_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += 2*L_ovov[k,c,l,d]*ct_vovo[a,i,c,k]*v_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += 2*cs_vovo[a,k,c,i]*g_ovov[k,d,l,c]*t_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += 2*cs_vovo[a,k,c,j]*g_ovov[k,d,l,c]*t_vovo[b,l,d,i]
        rho_vovo[a,i,b,j] += -2*cs_vovo[a,i,b,k]*g_ovov[k,c,l,d]*u_vovo[c,j,d,l]
        rho_vovo[a,i,b,j] += -2*cs_vovo[a,i,c,j]*g_ovov[k,c,l,d]*u_vovo[b,k,d,l]
        rho_vovo[a,i,b,j] += -2*cs_vovo[a,k,c,i]*g_ovov[k,c,l,d]*u_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += 2*ct_vovo[a,k,c,i]*g_ovov[k,d,l,c]*s_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += 2*ct_vovo[a,k,c,j]*g_ovov[k,d,l,c]*s_vovo[b,l,d,i]
        rho_vovo[a,i,b,j] += -2*ct_vovo[a,i,b,k]*g_ovov[k,c,l,d]*v_vovo[c,j,d,l]
        rho_vovo[a,i,b,j] += -2*ct_vovo[a,i,c,j]*g_ovov[k,c,l,d]*v_vovo[b,k,d,l]
        rho_vovo[a,i,b,j] += -2*ct_vovo[a,k,c,i]*g_ovov[k,c,l,d]*v_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += -L_ovov[k,c,l,d]*ct_vo[a,k]*s_vo[d,l]*t_vovo[b,j,c,i]
        rho_vovo[a,i,b,j] += -L_ovov[k,c,l,d]*ct_vo[c,i]*s_vo[d,l]*t_vovo[a,k,b,j]
        rho_vovo[a,i,b,j] += -L_ovov[k,c,l,d]*ct_vo[c,k]*s_vo[a,l]*t_vovo[b,j,d,i]
        rho_vovo[a,i,b,j] += -L_ovov[k,c,l,d]*ct_vo[c,k]*s_vo[d,i]*t_vovo[a,l,b,j]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_ovov[k,c,l,d]*s_vo[b,l]*t_vovo[c,i,d,j]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_ovov[k,c,l,d]*s_vo[d,i]*t_vovo[b,j,c,l]
        rho_vovo[a,i,b,j] += ct_vo[a,k]*g_ovov[k,c,l,d]*s_vo[d,j]*t_vovo[b,l,c,i]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_ovov[k,c,l,d]*s_vo[a,l]*t_vovo[b,j,d,k]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_ovov[k,c,l,d]*s_vo[b,l]*t_vovo[a,k,d,j]
        rho_vovo[a,i,b,j] += ct_vo[c,i]*g_ovov[k,c,l,d]*s_vo[d,j]*t_vovo[a,k,b,l]
        rho_vovo[a,i,b,j] += -ct_vo[a,k]*g_ovov[k,c,l,d]*s_vo[c,i]*u_vovo[b,j,d,l]
        rho_vovo[a,i,b,j] += -ct_vo[c,i]*g_ovov[k,c,l,d]*s_vo[a,k]*u_vovo[b,j,d,l]
    end
    finalize_eT_function("jacobian_qed_ccsd_electronic_s2", "qed_ccsd")
end

